version: 2

sources:
  - name: stage
    description: 'parquets landed from s3'
    schema: stage
    tables:
      - name: yellow_trip
        meta: 
          dagster: 
            asset_key: ['parquet_to_duckdb']